[package]
name = "orki-cli"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "orki"
path = "src/main.rs"

[dependencies]
orki-core = { path = "../../crates/orki-core", version = "0.0.1" }
orki-pack = { path = "../../crates/orki-pack", version = "0.0.1" }
orki-tauri = { path = "../../crates/orki-tauri", version = "0.0.1" }
orki-schema = { path = "../../crates/orki-schema", version = "0.0.1" }
toml = { workspace = true }

[lints]
workspace = true
