[package]
name = "orki-stub"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "orki-stub"
path = "src/main.rs"

[features]
default = ["full"]
full = ["gui"]
lite = ["gui"]
gui = ["dep:orki-ui"]
headless = []

[dependencies]
orki-core = { path = "../../crates/orki-core", version = "0.0.1" }
orki-pack = { path = "../../crates/orki-pack", version = "0.0.1" }
orki-ui = { path = "../../crates/orki-ui", version = "0.0.1", optional = true }

[lints]
workspace = true
